baseURL = 'https://reflexions.florianernotte.be/' 
languageCode = 'en-us'
title = 'reflexions '
theme = 'archiefork'
copyright = "© Florian Ernotte"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
  
[params]
mode= 'toggle'  
subtitle = 'Quelques expériences et reflexions sur le Web'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# Main menu Items

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "post"
url = "/post"
weight = 2

[[menu.main]]
name = "numérique"
url = "/numerique"
weight = 3

[[menu.main]]
name = "about"
url = "/about"
weight = 4

[[menu.main]]
name = "tags"
url = "/tags"
weight = 5
